### ISSUE TITLE
refactor: yml 파일 관리 방법 변경 -> github secret으로 관리

### ISSUE THREAD

**Issue by jusung-c** [HopeGaarden/MULAN#13]
## 어떤 기능인가요?

기존 암호화했던 설정 파일을 secret 파일로 관리하도록 변경한다.

**Comment by ThisGrDn** [comment]
application.yml 파일들을 변경하라는 뜻인가요?

**Comment by jusung-c** [comment]
@ThisGrDn 제가 변경한 담에 알려드릴게요~
